In [73]:
import cvxpy
import pandas
import numpy 
import matplotlib.pyplot as plot

In [14]:
q1x=numpy.loadtxt("code/q1x.dat")

q1x[0:10]

array([[ 1.3432504 , -1.3311479 ],
       [ 1.8205529 , -0.6346681 ],
       [ 0.98632067, -1.8885762 ],
       [ 1.9443734 , -1.635452  ],
       [ 0.97673352, -1.3533151 ],
       [ 1.9458584 , -2.0443278 ],
       [ 2.1075153 , -2.1256684 ],
       [ 2.070373  , -2.4634101 ],
       [ 0.86864964, -2.4119348 ],
       [ 1.8006594 , -2.7739689 ]])

In [19]:
q1y=numpy.loadtxt("code/q1y.dat")

q1y[0:10]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
X=q1x

y=2*(q1y-0.5)

C =1

m,n=numpy.shape(X)

m,n

(99, 2)

In [57]:
b=cvxpy.Variable()
w=cvxpy.Variable(n)
xi=cvxpy.Variable(m)

In [101]:
objective=cvxpy.Minimize( 1/2* sum( w* w.T  ) +C * sum(xi) )

In [102]:
constraints=[y*( (X*w)+b) >= 1- xi,xi >= 0]

In [103]:
prob=cvxpy.Problem(objective,constraints)

In [104]:
prob.solve(verbose=True)


ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +2.802e-10  +9.445e-02  +1e+02  9e-01  7e-02  1e+00  5e-01    ---    ---    1  1  - |  -  - 
 1  -9.693e-05  +1.037e-03  +1e+00  1e-02  8e-04  1e-02  6e-03  0.9890  1e-04   0  0  0 |  0  0
 2  -1.070e-06  +1.150e-05  +1e-02  1e-04  9e-06  1e-04  6e-05  0.9890  1e-04   0  0  0 |  0  0
 3  -1.180e-08  +1.276e-07  +1e-04  2e-06  1e-07  1e-06  7e-07  0.9890  1e-04   0  0  0 |  0  0
 4  -1.130e-10  +1.429e-09  +2e-06  2e-08  1e-09  2e-08  8e-09  0.9890  1e-04   0  0  0 |  0  0
 5  +3.998e-12  +2.049e-11  +2e-08  2e-10  2e-11  2e-10  9e-11  0.9890  1e-04   0  0  0 |  0  0
 6  +1.277e-13  +3.025e-13  +2e-10  2e-12  2e-13  2e-12  1e-12  0.9890  1e-04   0  0  0 |  0  0

OPTIMAL (within feastol=2.2e-12, reltol=6.2e+02, abstol=1.9e-10).
Runtime: 0.016238 seconds.



1.27714941393133e-13

In [71]:
xp = numpy.linspace(min(X[:,1]), max(X[:,1]), 100);
yp = - (w.value[0]*xp + b)/w.value[1];

yp1 = - (w.value[0]*xp + b - 1)/w.value[1];

yp0 = - (w.value[0]*xp + b + 1)/w.value[1];

idx0 = q1y[q1y==0];
idx1 = q1y[q1y==1];

In [78]:
w.value

matrix([[ 0.05165295],
        [ 0.04644358]])

In [79]:
xi.value

matrix([[  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.29004991e-15],
        [  1.2900499