熟读并实操课程中提供的案例代码，尝试用Python语言重写，同时思考如何用这个代码求取线性回归模型

In [2]:
import numpy as np
ln='-'*30

In [84]:
def gradient_method_quadratic(A,b,x0,epsilon):
    x=np.mat(x0)
    iters=0
    grad=2*(A*x+b);
    while (np.linalg.norm(grad)>epsilon):
        iters=iters+1;
        grad_norm=np.linalg.norm(grad);
        Grad=2*(grad.T)*A*grad;
        Grad=float(Grad)
        #print Grad,(grad_norm**2)
        t=grad_norm**2/Grad
        print x,t,grad
        x=x-t*grad;
        grad=2*(A*x+b);
        fun_val=x.T*A*x+2*b.T*x;
        print 'iter_number = %3d norm_grad = %2.6f fun_val = %2.6f \n' % (iters,grad_norm,fun_val);



In [85]:
A= np.array([[1,0],[0,2]])
b=np.array([[0],[0]])
x0=np.array([[2],[1]])
epsilon=1e-5

print A,ln,b,ln,x0,ln,epsilon


[[1 0]
 [0 2]] ------------------------------ [[0]
 [0]] ------------------------------ [[2]
 [1]] ------------------------------ 1e-05


In [86]:
gradient_method_quadratic(A,b,x0,epsilon)

[[2]
 [1]] 0.333333333333 [[4]
 [4]]
iter_number =   1 norm_grad = 5.656854 fun_val = 0.666667 

[[ 0.66666667]
 [-0.33333333]] 0.333333333333 [[ 1.33333333]
 [-1.33333333]]
iter_number =   2 norm_grad = 1.885618 fun_val = 0.074074 

[[ 0.22222222]
 [ 0.11111111]] 0.333333333333 [[ 0.44444444]
 [ 0.44444444]]
iter_number =   3 norm_grad = 0.628539 fun_val = 0.008230 

[[ 0.07407407]
 [-0.03703704]] 0.333333333333 [[ 0.14814815]
 [-0.14814815]]
iter_number =   4 norm_grad = 0.209513 fun_val = 0.000914 

[[ 0.02469136]
 [ 0.01234568]] 0.333333333333 [[ 0.04938272]
 [ 0.04938272]]
iter_number =   5 norm_grad = 0.069838 fun_val = 0.000102 

[[ 0.00823045]
 [-0.00411523]] 0.333333333333 [[ 0.01646091]
 [-0.01646091]]
iter_number =   6 norm_grad = 0.023279 fun_val = 0.000011 

[[ 0.00274348]
 [ 0.00137174]] 0.333333333333 [[ 0.00548697]
 [ 0.00548697]]
iter_number =   7 norm_grad = 0.007760 fun_val = 0.000001 

[[ 0.00091449]
 [-0.00045725]] 0.333333333333 [[ 0.00182899]
 [-0.00182899]]
iter

In [32]:
x=np.mat(x0)
grad=2*(A*x+b)

grad

matrix([[4],
        [4]])

In [35]:
2*(grad.T)*A*grad

matrix([[96]])

In [53]:
grad_norm=np.linalg.norm(grad)


grad_norm**2

32.000000000000007

In [71]:
Grad=2*(grad.T)*A*grad;

int(Grad)

96